http://cdimage-search.debian.org/<br>
https://www.debian.org/doc/<br>
https://www.debian.org/distrib/packages<br>
https://wiki.debian.org/SourcesList<br>
https://wiki.debian.org/DebianJessie<br>
https://wiki.debian.org/Mate<br>
https://wiki.debian.org/Root<br>
https://wiki.debian.org/sudo<br>
https://wiki.debian.org/Firmware<br>
https://wiki.debian.org/ALSA<br>
https://wiki.debian.org/PulseAudio<br>
https://wiki.debian.org/Multiarch/HOWTO<br>
https://wiki.debian.org/Locale<br>
https://wiki.debian.org/ChangeLanguage<br>
http://linux.die.net/man/1/su<br>
http://linux.die.net/man/1/gksudo<br>
